#+TITLE: Optional Argument in C++
#+PROPERTY: header-args:cpp :wrap example :results output :nomain :flags "-std=c++17 -Wall -I/home/picaud/GitHub/OptionalArgument/src/"

* What is it?

This is a C++17 *one* header file library that will allow you to define named optional arguments.

It can be used to improves code readability by replacing obscure
function/method calls like
#+BEGIN_SRC cpp :eval never
algorithm(x_init, 100, std::vector<double>(n, 0), std::vector<double>(n, 1), 1e-6, 1e-6)
#+END_SRC

By something like

#+BEGIN_SRC cpp :eval never
algorithm(x_init, max_iterations = 100, absolute_precision = 1e-6);
algorithm(x_init, absolute_precision = 1e-6, lower_bounds<double> = std::vector<double>(n, 0));
algorithm(x_init);
#+END_SRC
supporting all the variations in position/definition for the optional arguments.

The required boilerplate code to add optional
argument support is relatively light:

#+BEGIN_SRC cpp :eval never
template <typename T, typename... USER_OPTIONS>
void algorithm(std::vector<T>& x, const USER_OPTIONS&... user_options)
{
  Absolute_Precision absolute_precision = 1e-10;
  Max_Iterations max_iterations = 500;
  std::optional<Allows_Restart> allows_restart;

  auto options = take_optional_argument_ref(absolute_precision, max_iterations, allows_restart);
  optional_argument(options, user_options...);

  // ...
}
#+END_SRC

Basically it works by defining a =std::tuple<OPTIONS...>= which is
filled by the provided =user_options= at the site call.

** Installation 

The library currently uses the [[https://mesonbuild.com/][meson]] build system. Maybe I will add CMake
in the future, but as this library is only one header file you can
easily test it without any build system.

If you are not familiar with meson, the compilation procedure is as follows:

#+BEGIN_SRC sh :eval never
git clone git@github.com:vincent-picaud/OptionalArgument.git
cd OptionalArgument/
meson build
cd build
ninja test
#+END_SRC 

Examples can then be found in the =examples/= directory.

* Tutorial
** Basic usage 

The most "rustic" usage is:

#+begin_src cpp :eval no-export :exports both
#include <iostream>
#include "OptionalArgument/optional_argument.hpp"

using namespace OptionalArgument;

template <typename... Ts>
void example(Ts... user_options)
{
  int maximum_iterations = 50;
  double absolute_precision = 1e-5;
  std::optional<bool> allows_restart;

  auto options = take_optional_argument_ref(maximum_iterations, absolute_precision, allows_restart);
  optional_argument(options, user_options...);

  std::cout << "\nOption values: " << options;
}

int main()
{
  example(10);
  example(1e-6, std::optional<bool>(true));
  example();

  return EXIT_SUCCESS;
}
#+end_src

#+RESULTS:
#+BEGIN_example
Option values: 10 1e-05 
Option values: 50 1e-06 1 
Option values: 50 1e-05
#+END_example

Basically we define some optional arguments like
=absolute_precision=. Using a helper function
=take_optional_argument_ref()= we collect their references and store
them in the =options= object. Then optional argument values are
overwritten by =user_options= provided at the call site. This task is
performed by the =optional_argument()= function.

** =Named_Type=

#+BEGIN_QUOTE
Preamble: great blog posts about =Named_Typed= can be found [[https://www.fluentcpp.com/2016/12/08/strong-types-for-strong-interfaces/][here]]. This
was a source of inspiration but our implementation is different and
simpler as it only provides functionalities useful for our
=OptionalArgument= library.
#+END_QUOTE

There are several limitations if we stick to literal types
like =int, double, ...= :
- we cannot define several options of the same type,
- we cannot relies on implicit type conversion.

By example, if you try:

#+begin_src cpp :eval never :exports both
#include "OptionalArgument/optional_argument.hpp"
#include <iostream>

using namespace OptionalArgument;

template <typename... Ts>
void example(Ts... user_options)
{
  size_t maximum_iterations = 50;
  float absolute_precision = 1e-5;

  auto options = take_optional_argument_ref(maximum_iterations, absolute_precision);
  optional_argument(options, user_options...);

  std::cout << "\nOption values: " << options;
}

int main()
{
  example(10);    // does not work, one would have to use: example(size_t(10));
  example(1e-6);  // does not work, one would have to use: example(1e-6f);

  return EXIT_SUCCESS;
}
#+end_src

the library does not compile and returns you an error message:

#+begin_example
...
OptionalArgument/optional_argument.hpp:122:46: error: static assertion failed: Unexpected type
  122 |         static_assert((occurence_count != 0) && (occurence_count_maybe_optional != 0), "Unexpected type");
...
#+end_example

The solution is to use implicit type conversion and a different type
for each option.

This library provides a basic =Named_Type= class for
that. Please, note that you can use this library with any of your own class, it is by no
way mandatory to use the provided =Named_Type=. 

Using =Named_Type= the problematic initial code is fixed/rewritten as
follows:

#+begin_src cpp :eval no-export :exports both
#include "OptionalArgument/optional_argument.hpp"

#include <iostream>

using namespace OptionalArgument;

using Absolute_Precision = Named_Type<struct Absolute_Precision_Tag, double>;
constexpr auto absolute_precision = typename Absolute_Precision::argument_syntactic_sugar();

using Maximum_Iterations = Named_Type<struct Maximum_Iterations_Tag, size_t>;
constexpr auto maximum_iterations = typename Maximum_Iterations::argument_syntactic_sugar();

template <typename... Ts>
void example(Ts... user_options)
{
  Maximum_Iterations maximum_iterations = 50;
  Absolute_Precision absolute_precision = 1e-5;

  auto options = take_optional_argument_ref(maximum_iterations, absolute_precision);
  optional_argument(options, user_options...);

  std::cout << "\nOption values: " << options;
}

int main()
{
  example(maximum_iterations = 10);
  example(absolute_precision = 1e-6);

  return EXIT_SUCCESS;
}
#+end_src

#+RESULTS:
#+BEGIN_example
Option values: 10 1e-05 
Option values: 50 1e-06
#+END_example

** Without =Named_Type=

You can use this library without any reference to the =Named_Type= class (which is only
  provided for convenience). 

The example below shows how you can define optional arguments from
  scratch and use them.

#+BEGIN_SRC cpp :eval never
#include "OptionalArgument/optional_argument.hpp"

#include <iostream>
#include <random>

using namespace OptionalArgument;

struct Sample_Size
{
  size_t n;

  size_t
  value() const
  {
    return n;
  }
};

struct Truncated
{
};

static constexpr auto sample_size = Argument_Syntactic_Sugar<Sample_Size, size_t>();
static constexpr auto truncated   = Truncated();

template <typename... USER_OPTIONS>
void
generate_sample(USER_OPTIONS&&... user_options)
{
  //// Options ////
  //
  Sample_Size sample_size{10};
  std::optional<Truncated> truncated;

  auto options = take_optional_argument_ref(sample_size, truncated);
  optional_argument(options, std::forward<USER_OPTIONS>(user_options)...);

  //// Implementation ////
  //
  std::random_device rd{};
  std::mt19937 gen{rd()};

  std::normal_distribution<> d{0, 1};

  for (size_t i = 0; i < sample_size.value(); i++)
  {
    auto sample = d(gen);
    if (truncated.has_value())
    {
      sample = std::abs(sample);
    }
    std::cout << sample << std::endl;
  }
  std::cout << std::endl;
}

int
main()
{
  generate_sample();

  generate_sample(truncated);

  generate_sample(truncated, sample_size = 5);
}
#+END_SRC

* More examples

In the =examples/= directory you will find:

- =algorithm_usage_example.cpp= is an hypothetical optimization
  algorithm with several options, with some using the std::vector
  class.
#+BEGIN_SRC cpp :eval never
int
main()
{
  const size_t n = 4;
  std::vector<double> x_init(n);

  // Option values: 100 1e-10 1e-10
  optimization_algorithm(x_init);

  // Option values: 50 1e-10 1e-10 0 0 0 0
  optimization_algorithm(x_init, max_iterations = 50,
                         lower_bounds<double> = std::vector<double>(n, 0));

  // Option values: 50 1e-08 1e-10 0 0 0 0  1 1 1 1
  optimization_algorithm(x_init, max_iterations = 50, absolute_precision = 1e-8,
                         lower_bounds<double> = std::vector<double>(n, 0),
                         upper_bounds<double> = std::vector<double>(n, 1));
}
#+END_SRC

- =plot_usage_example.cpp= is another usage example that shows how one
  can easily generate gnuplot script commands with all their variations.

#+BEGIN_SRC cpp :eval never
int
main()
{
  // prints:
  // plot sin(x)  linetype 2 title "my curve 1"
  // replot cos(x) linewidth 4 title "my curve 2"
  //
  plot(std::cout, "sin(x)", line_type = 2, curve_title = "my curve 1");
  replot(std::cout, "cos(x)", line_width = 4, curve_title = "my curve 2");
}
#+END_SRC

* FAQ

-> your questions here :-)

